name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - feature

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker credentials
        env:
        run echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "{{secretes.DOCKER_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build -t naresh2546/todo-list-app:latest .

      - name: Push Docker Image
        run: docker push naresh2546/todo-list-app:latest
      
      - name: log out from Docker hub
        run: docker logout
          